### ISSUE TITLE
client without args errors with weird error

### ISSUE THREAD

**Issue by hroncok** [tradej/devassistant-c2s#19]
When we run client without args, the server produces traceback and client errors.

```
./server.py 
{'__ui__': 'json'}
Traceback (most recent call last):
  File "/home/churchyard/Dokumenty/RedHat/devassistant/client_server2/server/da_server/helpers.py", line 77, in process_run
    to_run.run()
  File "/home/churchyard/Dokumenty/RedHat/devassistant/devassistant/devassistant/path_runner.py", line 51, in run
    self._logging(self.parsed_args)
  File "/home/churchyard/Dokumenty/RedHat/devassistant/devassistant/devassistant/path_runner.py", line 18, in _logging
    self.path[-1].logging(parsed_args)
AttributeError: 'TopAssistant' object has no attribute 'logging'

Error processing request: "{"query": {"options": {"path": "", "arguments": {}}, "request": "run"}}" ('TopAssistant' object has no attribute 'logging')
```

```
./client.py 
Executing assistant...
Error Processing: Error processing request: 'TopAssistant' object has no attribute 'logging'
Run Finished with Errors
```

**Comment by tradej** [comment]
This is caused by the top level subparsers not having the `required` attribute set to `True`. This is trivial to fix, but I need to see how a better message than

```
client.py: error: the following arguments are required: subassistant_0
```

can be printed.
